version: "3"

services:
  db_postgresql_esports:
    image: "bitnami/postgresql"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=esportsdb
    volumes:
      - "pgdata:/bitnami/postgresql"
    networks:
      - app-network

  app-nlw-esports:
    build: .
    container_name: api-nlwesports
    depends_on:
      - db_postgresql_esports
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
